### ISSUE TITLE
[1.19] Forge breaking changes

### ISSUE THREAD

**Issue by Baggytrousers27** [tristankechlo/Improved-Vanilla#5]
Forges 41.0.64+ and 41.0.94+ introduce breaking changes for improvedvanilla-1.19-1.6.0.

[crashlog](https://github.com/tristankechlo/ImprovedVanilla/files/9136637/crash-2022-07-19_11.10.01-fml.txt)

**Comment by tristankechlo** [comment]
Thanks for reporting  
Should be fixed in the newest version 1.19-1.6.1
