### ISSUE TITLE
[1.19.2] Forge breaking changes MKII: Electric Boogaloo.

### ISSUE THREAD

**Issue by Baggytrousers27** [tristankechlo/Improved-Vanilla#6]
Forge 1.19.2 43.1.30 (Works with 1.19.2 43.1.27 and below)
improvedvanilla-1.19-1.6.1

Improved Vanilla (improvedvanilla) has failed to load correctly
java.lang.reflect.InvocationTargetException: null

[crashlog.txt](https://github.com/tristankechlo/ImprovedVanilla/files/9665056/crash-2022-09-28_22.45.20-fml.txt)

Just as soon as everything's working smoothly a forge update comes in a breaks everything.

**Comment by tristankechlo** [comment]
should be fixed with the newest update

**Comment by Baggytrousers27** [comment]
Got good news and bad news. The good news is, improvedvanilla-forge-1.19.2-1.6.2, loads in. The bad news is that you can't open chests with it loaded.

Forge 1.19.2 43.1.52

[debug.log](https://github.com/tristankechlo/ImprovedVanilla/files/9973401/debug.log)

**Comment by tristankechlo** [comment]
This does not happen for me,  
the debug.log has no errors related to this either

**Comment by Baggytrousers27** [comment]
Just made a fresh installation of Forge 43.1.52, installed improvedvanilla-forge-1.19.2-1.6.2, made a new survival world with cheats enabled and a starting chest (Seed 2693683244939070593). Jumped off the spawn tree on onto a nearby lilypad, right clicked the starter chest that spawned over the water and nothing happens.

[debug.log](https://github.com/tristankechlo/ImprovedVanilla/files/9989469/debug.log)

Reopened mc and loaded back into the world, switched to creative, gave myself a chest, placed the chest and right clicked it. Nothing.

[debug.log 2](https://github.com/tristankechlo/ImprovedVanilla/files/9989526/debug.log)


The only things changed in options are swapping Shift and Ctrl to sprint and crouch, tab to open inventory (no key assigned to list players), turned the master volume and music down, turned off mipmap and smooth lighting, changed gui scale to 3 and changed all the fancy/fabulous visuals to fast.

Removed improvedvanilla-forge-1.19.2-1.6.2 from installation, reopened MC and world, right clicked both chests. Both chests opened.

[debug.log 3](https://github.com/tristankechlo/ImprovedVanilla/files/9989553/debug.log).

Any ideas what to try next?

**Comment by tristankechlo** [comment]
Now I have this issue too,  
even more strange, I can only open chests when I have a chest in my mainhand  
will test some more things and figure out what's causing this
