### ISSUE TITLE
Right-Click harvest config breaks opening / operating things with open hand [1.19.2]

### ISSUE THREAD

**Issue by KinamKrindar** [tristankechlo/Improved-Vanilla#7]
Building a makeshift personal pack that has a ton of different mods. Noted that whenever having an open hand (nothing in it), nothing could be operated / opened without shift-right clicking on it. Unfortunately this was highly annoying when trying to do stuff with Create mod as shift-right clicking does not function for some of the things. Attempting to open doors with an open hand would quickly open and close the door graphically, but the hitbox never opened to allow passage. 

Going into the config and turning OFF the right-click harvest setting, fixed these issues. 

Again, I have a _ton_ of mods in this self-made pack, so it's basically impossible to list them all here. However, I did disable everything, and start enabling one mod at a time and turned off previous mods and re-started a world with a chest in front of me, just to see if I could open it up ... only when ImprovedVanilla was enabled did the issue come up.

**Comment by tristankechlo** [comment]
Thank you for reporting, I know of this bug and it will be fixed in the next update
