### ISSUE TITLE
[1.19.3] still giving exp

### ISSUE THREAD

**Issue by vaniron** [tristankechlo/Improved-Vanilla#8]
Still giving out exp when breaking that spawners with silktouch and spawner_drop_chance set to 100. Creating possibility to place them and break again for easy exp farm.

**Comment by tristankechlo** [comment]
Are you using forge or fabric?

**Comment by vaniron** [comment]
fabric

**Comment by tristankechlo** [comment]
Yeah, this is only for the fabric version, forge does not have this problem  
forge offers a convenient way to remove exp drops, fabric does not

**Comment by tristankechlo** [comment]
found no solution to achieve the same effect on fabric
